import React, { Component } from 'react'

export class Disclaimer extends Component {
  render() {
    return (
      <div>
  <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
  <h1>Disclaimer</h1>
  <p>Updated at 2022-06-13</p>
  <p>Tifinco hereby grants you access to https://tifinco.com/ (“the Website”) and invites you to purchase the services offered here.</p>
  <h1>Definitions and key terms</h1>
  <p>To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, are strictly defined as:</p>
  <ul>
    <li>Cookie:&nbsp;small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
    <li>Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Tifinco, UNI HOMES PARISHAR KRAMANK-167 BHATAGAON RAIPUR CHHATTISGARH that is responsible for your information under this Disclaimer.</li>
    <li>Service: refers to the service provided by Tifinco as described in the relative terms (if available) and on this platform.</li>
    <li>Website:  site, which can be accessed via this URL: https://tifinco.com/</li>
    <li>You: a person or entity that is registered with Tifinco to use the Services.</li>
  </ul>
  <p>This Disclaimer was created with <a href="https://termify.io/" target="_blank">Termify</a>.</p>
  <h1>Limited liability</h1>
  <p>Tifinco endeavours to update and/or supplement the content of the website/app on a regular basis. Despite our care and attention, content may be incomplete and/or incorrect.</p>
  <p>The materials offered on the website/app are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from Tifinco.</p>
  <p>Particularly, all prices on the website/app are stated subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors.</p>
  <p>Tifinco shall not bear any liability for hyperlinks to websites or services of third parties included on the website/app. From our website/app, you can visit other websites by following hyperlinks to such external sites. While we strive to provide only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content may change without notice and may occur before we have the opportunity to remove a link which may have gone ‘bad’.</p>
  <p>Please be also aware that when you leave our website/app, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before engaging in any business or uploading any information.</p>
  <h1>Errors and Omissions Disclaimer</h1>
  <p>Tifinco is not responsible for any content, code or any other imprecision.</p>
  <p>Tifinco does not provide warranties or guarantees.</p>
  <p>In no event shall Tifinco be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. Tifinco reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</p>
  <h1>General Disclaimer</h1>
  <p>The Tifinco Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Tifinco is a distributor and not a publisher of the content supplied by third parties; as such, Tifinco exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the Tifinco Service.
    Without limiting the foregoing, Tifinco specifically disclaims all warranties and representations in any content transmitted on or in connection with the Tifinco Service or on sites that may appear as links on the Tifinco Service, or in the products provided as a part of, or otherwise in connection with, the Tifinco Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by Tifinco or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, Tifinco does not warrant that the Tifinco Service will be uninterrupted, uncorrupted, timely, or error-free.</p>
  <h1>Copyright Disclaimer</h1>
  <p>All intellectual property rights concerning these materials are vested in Tifinco. Copying, distribution and any other use of these materials is not permitted without the written permission of Tifinco, except and only to the extent otherwise provided in regulations of mandatory law (such as the right to quote), unless otherwise stated for certain materials.</p>
  <h1>Health Disclosure</h1>
  <p>The information on this website/app such as text, graphics, images, and other materials created by Tifinco or obtained from  licensors, and other materials contained on Tifinco (collectively, “content”) is intended solely for informational purposes and may not be used as a substitute for professional advice and/or information, as circumstances will vary from person to person. You should not act or rely upon this information without seeking professional advice. Do not attempt any of the suggested actions, solutions, remedies, or instructions found on this website/app without first consulting with a qualified professional. The materials are not intended to be nor do they constitute actionable professional advice. Transmissions of this information is not intended to create a professional-client relationship between Level Up Enterprises and you. The owners, editors, contributors, administrators, and other staff of Level Up Enterprises are not qualifies professionals, and are simply aggregating information found online for informational purposes only.</p>
  <p>If you think you may have a medical emergency, call your doctor or 911 immediately. Tifinco does not recommend or endorse any specific tests, physicians, products, procedures, opinions, or other information that may be mentioned on the website/app. Reliance on any information provided by Tifinco, Tifinco employees, others appearing on the website/app at the invitation of Tifinco, or other visitors to the website/app is solely at your own risk.</p>
  <h1>Legal Disclosure</h1>
  <p>The materials, any comments or information provided by Tifinco are for educational purposes only and nothing conveyed or provided should be considered legal, accounting or tax advice. You are responsible for whatever you may do with the information you obtain from Tifinco. As such, by visiting and using this website/app you acknowledge and agree that you have been assessed by a qualified law expert (i.e your attorney) who has given you consent to take part in any legal activity. Please contact your own attorney, accountant or tax professional with any specific questions you have related to the information provided that are of legal, accounting or tax nature.</p>
  <h1>Testimonials Disclosure</h1>
  <p>Any testimonials provided on this platform are opinions of those providing them. The information provided in the testimonials is not to be relied upon to predict results in your specific situation. The results you experience will be dependent on many factors including but not limited to your level of personal responsibility, commitment, and abilities, in addition to those factors that you and/or Tifinco may not be able to anticipate.</p>
  <p>We will give honest testimonials to our visitors regardless of any discount. Any product or service that we test are individual experiences, reflecting real life experiences. The testimonials could be displayed on audio, text or video and are not necessarily representative of all of those who will use our products and/or services.</p>
  <p>Tifinco does not guarantee the same results as the testimonials given on our platform. Testimonials presented on Tifinco are applicable to the individuals writing them, and may not be indicative of future success of any other individuals.</p>
  <p>Please don’t hesitate to contact us if you would like to know more about testimonials, discounts, or any of the products/services that we review.</p>
  <h1>Your Consent</h1>
  <p>We've updated our&nbsp;Disclaimer&nbsp;to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website/app, registering an account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms.</p>
  <h1>Changes To Our Disclaimer</h1>
  <p>Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete your account.</p>
  <h1>Contact Us</h1>
  <p>Don't hesitate to contact us if you have any questions regarding this Disclaimer.</p>
  <ul><li>Via Email:  care@tifinco.com</li><li>Via Phone Number:  0771-4040088</li><li>Via this Link:  https://tifinco.com/contact-us</li>
  </ul>
</div>

    )
  }
}

export default Disclaimer